name: Pipeline

on:
 push: 
   branches: 
     - 'master'

jobs:
 Checkout:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout current repository
    uses: actions/checkout@v3
  - name: Checkout another repo
    uses: actions/checkout@v3
    with:
      repository: Nikhil955/HelloWorldJava
      ref: master
  - name: Run PowerShell script
    run: |
        # Navigate to the directory where the repository was cloned

        # Run your PowerShell script
        powershell -File main.ps1
  #- name: run script
  #  shell: pwsh
   # run: ./main.ps1 -Task ModuleBuild
 Build:
  runs-on: ubuntu-latest
  steps:
  - name: Build with Gradle
  # You may pin to the exact commit or the version.
  # uses: gradle/actions@ed408507eac070d1f99cc633dbcf757c94c7933a
    uses: gradle/actions@v4.4.3
          
 sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: 33a274b8d023af19b6c8add08b72be102cfdb180



        
