name: RunPscript

on:
 push: 
   branches: 
     - 'master'

jobs:
 runscript:
  runs-on: self-hosted
  steps:
  - name: Checkout repo
    uses: actions/checkout@v3
    with:
      repository: Nikhil@955/HelloWorldJava
      path: main.ps1
      ref: master
  - name: run script
    shell: pwsh
    run: ./main.ps1 -Task ModuleBuild
     
        
