name: RunPscript

on:
 push: 
   branches: 
     - 'master'

jobs:
 runscript:
  runs-on: self-hosted
  steps:
  - name: Checkout current repository
    uses: actions/checkout@v3
  - name: Checkout another repo
    uses: actions/checkout@v3
    with:
      repository: Nikhil955/HelloWorldJava
      ref: master
  - name: Run PowerShell script
    run: |
        # Navigate to the directory where the repository was cloned

        # Run your PowerShell script
        powershell -File main.ps1
  #- name: run script
  #  shell: pwsh
   # run: ./main.ps1 -Task ModuleBuild
     
        
